server {
    listen 80;

    # Default server configuration for NGINX
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 'OK';
    }
}
