server {
    listen 80;

    # Default server configuration for NGINX
    location / {
        root   /usr/share/nginx/html;
        index  index.html;

        # Health check endpoint inside the root location block
        access_log off;
        try_files $uri $uri/ =404;
    }

    # Health check endpoint
    location = /health {
        access_log off;
        return 200 'OK';
    }
}
