apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}  
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      name: {{ .Values.appname }}  
      labels:
        app: {{ .Values.appname }}  
    spec:
      serviceAccountName: {{ include "helm-project.serviceAccountName" . }}
      containers:
        - name: mycontainer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /   # Ensure the health check URL is correct
              port: 80      # The port your app is listening on
            initialDelaySeconds: 15  # Delay before the probe starts
            periodSeconds: 10       # Frequency of the probe
            failureThreshold: 3     # How many failures before the pod is considered unhealthy
          readinessProbe:
            httpGet:
              path: /  # Ensure the readiness check URL is correct
              port: 80      # The port your app is listening on
            initialDelaySeconds: 15  # Delay before the probe starts
            periodSeconds: 10       # Frequency of the probe
            failureThreshold: 3     # How many failures before the pod is considered not ready
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
