apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: {{ .Values.appname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appname }}