apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: {{ .Values.appname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80               # Expose service on port 80
      targetPort: 80       # Application listens on port 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appname }}
